/**
 * Auto-generated Convex data model types.
 * This file is generated by `npx convex dev` at runtime.
 * The actual generated file will be created when you run `npx convex dev` with your CONVEX_DEPLOYMENT key.
 */

import type { GenericDataModel, GenericDocument } from "convex/server";

export type TableNames =
  | "trades"
  | "learningRecords"
  | "patterns"
  | "botConfig"
  | "botState"
  | "signals"
  | "strategyPerformance";

export type Id<T extends TableNames = TableNames> = string & { __tableName: T };

export type Doc<T extends TableNames> = GenericDocument & {
  _id: Id<T>;
  _creationTime: number;
};

export type DataModel = GenericDataModel;
