/**
 * Auto-generated Convex server types.
 * This file is generated by `npx convex dev` at runtime.
 * The actual generated file will be created when you run `npx convex dev` with your CONVEX_DEPLOYMENT key.
 */

import type { MutationBuilder, QueryBuilder, ActionBuilder } from "convex/server";
import type { DataModel } from "./dataModel";

export type MutationCtx = {
  db: any;
  auth: any;
  storage: any;
  scheduler: any;
};

export type QueryCtx = {
  db: any;
  auth: any;
  storage: any;
};

export type ActionCtx = {
  runQuery: any;
  runMutation: any;
  runAction: any;
  auth: any;
  storage: any;
  scheduler: any;
};

export declare const mutation: MutationBuilder<DataModel, "public">;
export declare const query: QueryBuilder<DataModel, "public">;
export declare const action: ActionBuilder<DataModel, "public">;
export declare const internalMutation: MutationBuilder<DataModel, "internal">;
export declare const internalQuery: QueryBuilder<DataModel, "internal">;
export declare const internalAction: ActionBuilder<DataModel, "internal">;
